"""
models/plan.py — Pydantic models for Human-in-the-Loop Plan Approval.

Defines PlanState lifecycle (PENDING, APPROVED, REJECTED, MODIFIED),
LogisticsPlan container, and decision response schemas.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field

from app.models.optimization import OptimizationDelivery


class PlanState(str, Enum):
    """Lifecycle state of an optimization delivery plan."""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"


class LogisticsPlan(BaseModel):
    """
    A complete logistics plan recommendation generated by the optimizer or COA engine.
    """
    id: str = Field(..., description="Unique plan identifier")
    name: str = Field(default="OPTIMAL_RECOMMENDATION", description="Descriptive name or strategic profile")
    status: PlanState = Field(default=PlanState.PENDING, description="Current approval status")
    deliveries: List[OptimizationDelivery] = Field(
        default_factory=list,
        description="Delivery vehicle assignments and routes",
    )
    total_supplied: float = Field(default=0.0, description="Total quantity of supplies dispatched")
    total_unmet_demand: float = Field(default=0.0, description="Total unsatisfied demand")
    total_distance: float = Field(default=0.0, description="Total transit mileage in km")
    total_eta: float = Field(default=0.0, description="Total delivery duration in hours")
    estimated_cost: float = Field(default=0.0, description="Estimated operational logistics cost")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Plan creation timestamp",
    )
    decided_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when human operator approved or rejected the plan",
    )
    decision_reason: Optional[str] = Field(
        default=None,
        description="Optional notes or justification from operator",
    )

    model_config = {"frozen": False}


class PlanDecisionRequest(BaseModel):
    """Optional payload for plan approval or rejection."""
    reason: Optional[str] = Field(
        default=None,
        description="Optional justification note from operator",
    )

    model_config = {"frozen": False}


class PlanDecisionResponse(BaseModel):
    """Response returned upon approving or rejecting a plan."""
    plan_id: str = Field(..., description="ID of the plan")
    status: PlanState = Field(..., description="New plan status (APPROVED / REJECTED)")
    message: str = Field(..., description="Human-readable decision summary")
    plan: LogisticsPlan = Field(..., description="Full plan details")
    is_active: bool = Field(..., description="True if this plan is now active in the simulation state")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp of the decision",
    )

    model_config = {"frozen": False}
