"""
models/reoptimization.py — Pydantic models for dynamic re-optimization following disruptions.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field

from app.models.disruption import DisruptionRequest, DisruptionResult
from app.models.logistics_state import LogisticsState
from app.models.optimization import OptimizationDelivery, OptimizationResult, OptimizerWeights


class ReoptimizeRequest(BaseModel):
    """
    Request model for POST /api/reoptimize.

    Attributes:
        disruption:     The disruption event triggering re-optimization.
        state:          Optional custom LogisticsState. If None, uses current world state.
        previous_plan:  Optional baseline plan to compare against. If None, computed before disruption.
        weights:        Optional CP-SAT objective weights.
    """

    disruption: DisruptionRequest = Field(
        ...,
        description="The operational disruption event triggering the re-optimization cycle",
    )
    state: Optional[LogisticsState] = Field(
        default=None,
        description="Optional custom LogisticsState. If omitted, uses active in-memory world state.",
    )
    previous_plan: Optional[OptimizationResult] = Field(
        default=None,
        description="Optional baseline optimization plan. If omitted, solved automatically from baseline.",
    )
    weights: Optional[OptimizerWeights] = Field(
        default=None,
        description="Optional configurable solver weights.",
    )

    model_config = {"frozen": False}


class ReoptimizationResult(BaseModel):
    """
    Detailed comparative outcome of a dynamic re-optimization run.

    Attributes:
        trigger:              Disruption event description or type that triggered re-optimization.
        disruption_event:     Detailed disruption event metadata.
        affected_deliveries:  Deliveries in previous plan invalidated by the disruption.
        affected_vehicles:    Vehicle IDs compromised or unavailable.
        affected_routes:      Route IDs blocked or compromised.
        previous_eta:         Total estimated delivery duration from the previous plan (hours).
        new_eta:              Total estimated delivery duration from the re-optimized plan (hours).
        delay:                Calculated schedule delay / variance in hours (new_eta - previous_eta).
        previous_plan:        The baseline optimization result before disruption.
        new_plan:             The fresh optimization result recalculated from the disrupted state by CP-SAT.
        unmet_demand:         Remaining unmet demands per demand point in the new plan.
        optimization_status:  CP-SAT solver status for the new plan (e.g. OPTIMAL, FEASIBLE).
    """

    trigger: str = Field(..., description="Trigger summary string (e.g. 'BLOCK_ROUTE:ROUTE-03')")
    disruption_event: Optional[DisruptionResult] = Field(
        default=None,
        description="Disruption event details",
    )
    affected_deliveries: List[OptimizationDelivery] = Field(
        default_factory=list,
        description="Deliveries in previous plan compromised by the disruption",
    )
    affected_vehicles: List[str] = Field(
        default_factory=list,
        description="Vehicles disabled or impacted",
    )
    affected_routes: List[str] = Field(
        default_factory=list,
        description="Routes blocked or impacted",
    )
    previous_eta: float = Field(..., ge=0.0, description="Sum of ETAs in previous plan (hours)")
    new_eta: float = Field(..., ge=0.0, description="Sum of ETAs in new plan (hours)")
    delay: float = Field(..., description="Schedule delay variance (hours)")
    previous_plan: OptimizationResult = Field(..., description="Original baseline optimization plan")
    new_plan: OptimizationResult = Field(..., description="Re-calculated plan generated by CP-SAT")
    unmet_demand: Dict[str, Dict[str, float]] = Field(
        default_factory=dict,
        description="Unsatisfied demand in the new plan",
    )
    optimization_status: str = Field(..., description="CP-SAT status of the new plan")

    model_config = {"frozen": False}
